blogproject/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

# regular expression   re正则简写
app_name = 'blog'  #' 告诉 Django 这个 urls.py 模块是属于 blog 应用的  这种技术叫做视图函数命名空间

'''
# 在 Django 中 URL 模式的
# 配置方式就是通过 url 函数将 URL 和视图函数绑定。比如 url(r'^$', views.index,
# name='index')，它的第一个参数是 URL 模式，第二个参数是视图函数 index。
# 对 url 函数 来说，第二个参数传入的值必须是一个函数
'''  # url 函数

urlpatterns = [
    # url(r'^$',views.index,name='index'),  #普通视图
    url(r'^$',views.IndexView.as_view(),name='index'),  #类视图
    #将类视图转换成函数视图非常简单，只需调用类视图的 as_view() 方法即可

    # 访问 /archives/2017/3/，那么 archives 视图函
    # 数的实际调用为：archives(request, year=2017, month=3)。
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives,name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),

    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),

    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),  # post/1
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),  # post/1

    # 标签视图函数
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),


]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('blog.urls',namespace='blog')),
    url(r'^', include('comments.urls')),

    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),

]

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),

]



blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.six import python_2_unicode_compatible
from markdown import Markdown
import markdown
from django.utils.html import strip_tags




# 标签数据库表
class Tag(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name


# 分类数据库表
class Category(models.Model):
    name = models.CharField(max_length=100)
    def __str__(self):
        return self.name



# 文章（Post）
@python_2_unicode_compatible    # ??????
class Post(models.Model):
    # 文章标题
    title = models.CharField(max_length=70)

    # 存储比较短的字符串可以使用 CharField，但对于文章的正文来说可能会是一大段文本，因此使用TextField来存储大段文本。
    # 文章正文，我们使用了 TextField。注意不需要加参数
    body = models.TextField()

    # 这两个列分别表示文章的创建时间和最后一次修改时间，存储时间的字段用DateTimeField类型。
    created_time = models.DateTimeField(auto_now_add=True)   #自动赋值不能修改
    modified_time = models.DateTimeField(auto_now=True) #default=timezone.now修改时自动赋值能修改（auto_now_add不能修改）

    # 文章摘要，可以没有文章摘要，但默认情况下 CharField 要求我们必须存入数据，否则就会报错。
    # 指定 CharField 的 blank=True 参数值后就可以允许空值了。
    excerpt = models.CharField(max_length=200, blank=True)


    # 我们规定一篇文章只能对应一个分类，但是一个分类下可以有多篇文章，所以我们使用的是ForeignKey，即一对多的关联关系。
    # 而对于标签来说，一篇文章可以有多个标签，同一个标签下也可能有多篇文章，所以我们使用ManyToManyField，表明这是多对多的关联关系
    # 如果你对 ForeignKey、ManyToManyField 不了解，请看教程中的解释，亦可参考官方文档：
    # https://docs.djangoproject.com/en/1.10/topics/db/models/#relationships

    #  分类          一对多的关联关系  关联对象
    category = models.ForeignKey(Category)
    #  标签         多对多的关联关系
    tags = models.ManyToManyField(Tag, blank=True)

    # 因为我们规定一篇文章只能有一个作者，而一个作者可能会写多篇文章，因此这是一对多的关联关系，和Category类似。
    #  作者          一对多的关联关系/关联对象
    author = models.ForeignKey(User)


    def get_absolute_url(self):
        # 使用reverse函数，生成一个url，例如 post / 1
        return reverse('blog:detail', kwargs={'pk': self.pk})  #



    class Meta:
        ordering = ['-created_time']  #ordering 属性用来指定文章排序方式  ['-created_time'] 指定了依据哪个属性的值进行排序
        # 负号表示逆序排列。列表中可以用多个 项，比如ordering = ['-created_time', 'title']

    # 新增 views 字段记录阅读量
    views = models.PositiveIntegerField(default=0)
    # 一旦用户访问了某篇文章，这时就应该将views的值 + 1，这个过程最好由 Post模型自
    # 己来完成，因此再给模型添加一个自定义的方法：

    def increase_views(self):   #只需在视图函数中调用模型的 increase_views 方法即可。
        self.views += 1
        self.save(update_fields=['views'])

    # def save(self, *args, **kwargs):
    #     # 如果没有填写摘要
    #     if not self.excerpt:
    #         # 首先实例化一个 Markdown 类，用于渲染 body 的文本
    #         md = markdown.Markdown(extensions=[
    #             'markdown.extensions.extra',
    #             'markdown.extensions.codehilite',
    #         ])  # 先将 Markdown 文本渲染成 HTML 文本
    #
    #         # strip_tags 去掉 HTML 文本的全部 HTML 标签
    #         # 从文本摘取前 54 个字符赋给 excerpt
    #         self.excerpt = strip_tags(md.convert(self.body))[:54]
    #     super().save(*args, **kwargs)

    def save(self, *args, **kwargs):  #创建数据库存储时调用
        if not self.excerpt:
            md = Markdown(extensions=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            self.excerpt = strip_tags(md.convert(self.body))[:32]
        super().save(*args, **kwargs)


    def __str__(self):
        return self.title

blogproject/comments/models.py
from django.db import models

# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)   #评论用户的 name（名字）、
    email = models.EmailField(max_length=255) #评论用户的 email（邮箱）
    url = models.URLField(blank=True)         #评论用户的 url（个人网站）
    text = models.TextField()     # 用户发表的 内容将存放在 text 字段里
    created_time = models.DateTimeField(auto_now_add=True) #记录用户发表评论的时间  自动添加
    post = models.ForeignKey('blog.Post')       #关联到某篇文章（Post）

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post,Category,Tag
from django.views.generic import ListView,DetailView
import markdown
from comments.forms import CommentForm

'''
# def index(request):
#     post_list = Post.objects.all()  #  Post.objects.all() 从数据库中获取文章（Post）列表数据，并将其保存到 post_list 变量中。
#     return render(request,'blog/index.html',context={'post_list':post_list,})
'''  # 将 index 视图函数改写为类视图
'''
# index 视图函数首先通过 Post.objects.all() 从数据库中获取文章（Post）列表数据，
# 并将其保存到 post_list 变量中。而在类视图中这个过程 ListView 已经帮我们做了。
# 我们只需告诉 ListView 去数据库获取的模型是 Post，而不是 Comment 或者其它什
# 么模型，即指定 model = Post。将获得的模型数据列表保存到 post_list 里，即指
# 定 context_object_name = 'post_list'。然后渲染 blog/index.html 模板文件，index 视
# 图函数中使用 render 函数。但这个过程 ListView 已经帮我们做了，我们只需指定
# 渲染哪个模板即可。

'''  #IndexView
class IndexView(ListView): #   类视图
    model = Post   #model：将 model 指定为 Post，告诉 Django 我要获取的模型是 Post。
    template_name = 'blog/index.html'  #template_name：指定这个视图渲染的模板。
    context_object_name = 'post_list' # 这个name不能瞎取，必须和模板中的变量一直 context_object_name：指定获取的模型列表数据保存的变量名。这个变量会被传递给模板。

    # 类视图ListView已经帮我们写好了上述的分页逻辑，我们只需通过指定paginate_by属性来开启分页功能即可，
    # 即在类视图中指定paginate_by属性的值：
    paginate_by = 2   # 指定 paginate_by 属性后开启分页功能，其值代表每一页包含多少篇文章

    # Pagination 完善分页
    def get_context_data(self, **kwargs):
        """
        在视图函数中将模板变量传递给模板是通过给 render 函数的 context 参数传递一个字典实现的，
        例如 render(request, 'blog/index.html', context={'post_list': post_list})，
        这里传递了一个 {'post_list': post_list} 字典给模板。
        在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的，
        所以我们复写该方法，以便我们能够自己再插入一些我们自定义的模板变量进去。
        """

        # 首先获得父类生成的传递给模板的字典。
        context = super().get_context_data(**kwargs)
        # 父类生成的字典中已有 paginator、page_obj、is_paginated 这三个模板变量，

        # paginator 是 Paginator 的一个实例，
        # page_obj 是 Page 的一个实例，
        # is_paginated 是一个布尔变量，用于指示是否已分页。
        # 例如如果规定每页 10 个数据，而本身只有 5 个数据，其实就用不着分页，此时is_paginated=False。
        # 关于什么是 Paginator，Page 类在 Django Pagination 简单分页：http://zmrenwu.com/post/34/ 中已有详细说明。

        # 由于 context 是一个字典，所以调用 get 方法从中取出某个键对应的值。
        paginator = context.get('paginator')  #paginator ，即 Paginator 的实例。
        page = context.get('page_obj')  #page_obj ，当前请求页面分页对象。
        is_paginated = context.get('is_paginated')  #is_paginated，是否已分页。只有当分页后页面超过两页时才算已分页。

        # 调用自己写的 pagination_data 方法获得显示分页导航条需要的数据，见下方。
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将分页导航条的模板变量更新到 context 中，注意 pagination_data 方法返回的也是一个字典。
        context.update(pagination_data)
        # 将更新后的 context 返回，以便 ListView 使用这个字典中的模板变量去渲染模板。
        # 注意此时 context 字典中已有了显示分页导航条所需的数据。
        return context
    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，则无需显示分页导航条，不用任何分页导航条的数据，因此返回一个空的字典
            return {}

        left = []  # 当前页左边连续的页码号，初始值为空
        right = []   # 当前页右边连续的页码号，初始值为空

        left_has_more = False  # 标示第 1 页页码后是否需要显示省略号
        right_has_more = False  # 标示最后一页页码前是否需要显示省略号
        # 标示是否需要显示第 1 页的页码号。
        # 因为如果当前页左边的连续页码号中已经含有第 1 页的页码号，此时就无需再显示第 1 页的页码号，
        # 其它情况下第一页的页码是始终需要显示的。
        first = False   # 初始值为 False
        # 标示是否需要显示最后一页的页码号。
        # 需要此指示变量的理由和上面相同。
        last = False

        # 获得用户当前请求的页码号
        page_number = page.number

        # 获得分页后的总页数
        total_pages = paginator.num_pages

        # 获得整个分页页码列表，比如分了四页，那么就是 [1, 2, 3, 4]
        page_range = paginator.page_range

        if page_number == 1:  #??????????????????????????????????????????????????????????????????????????????
            # 如果用户请求的是第一页的数据，那么当前页左边的不需要数据，因此 left=[]（已默认为空）。
            # 此时只要获取当前页右边的连续页码号，
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 right = [2, 3]。
            # 注意这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。切片时如果溢出自动截断
            right = page_range[page_number:page_number + 2] #获取了当前页码后连续两个页码
            # 如果最右边的页码号比最后一页的页码号减去 1 还要小，
            # 说明最右边的页码号和最后一页的页码号之间还有其它页码，因此需要显示省略号，通过 right_has_more 来指示。
            if right[-1] < total_pages - 1:
                right_has_more = True
                # 如果最右边的页码号比最后一页的页码号小，说明当前页右边的连续页码号中不包含最后一页的页码

                # ??????????????????????????????????????????????????????????????????????????????
            # 所以需要显示最后一页的页码号，通过 last 来指示
            if right[-1] < total_pages:
                last = True
        elif page_number == total_pages:
            # 如果用户请求的是最后一页的数据，那么当前页右边就不需要数据，因此 right=[]（已默认为空），
            # 此时只要获取当前页左边的连续页码号。
            # 比如分页页码列表是 [1, 2, 3, 4]，那么获取的就是 left = [2, 3]
            # 这里只获取了当前页码后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            # 如果最左边的页码号比第 2 页页码号还大，
            # 说明最左边的页码号和第 1 页的页码号之间还有其它页码，因此需要显示省略号，通过 left_has_more 来指示。
            if left[0] > 2:
                left_has_more = True
            # 如果最左边的页码号比第 1 页的页码号大，说明当前页左边的连续页码号中不包含第一页的页码，
            # 所以需要显示第一页的页码号，通过 first 来指示
            if left[0] > 1:
                first = True
        else:
            # 用户请求的既不是最后一页，也不是第 1 页，则需要获取当前页左右两边的连续页码号，
            # 这里只获取了当前页码前后连续两个页码，你可以更改这个数字以获取更多页码。
            left = page_range[(page_number - 3) if (page_number - 3) > 0 else 0:page_number - 1]
            right = page_range[page_number:page_number + 2]
            # 是否需要显示最后一页和最后一页前的省略号
            if right[-1] < total_pages - 1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True
            # 是否需要显示第 1 页和第 1 页后的省略号
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }
        return data






'''  # category 视图函数的功能也是从数据库中获取文章列表数据
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})
'''  # category 视图函数的功能也是从数据库中获取文章列表数据
class CategoryView(IndexView):  # ListView -> IndexView继承
    # model = Post
    # template_name = 'blog/index.html'
    # context_object_name = 'post_list'
    #
    '''
    # 覆写了父类的 get_queryset 方法。该方法默认获
    # 取指定模型的全部列表数据。为了获取指定分类下的文章列表数据，我们覆写该
    # 方法，改变它的默认行为。
    # 从URL 捕获的命名组参数值保存在实例的 kwargs 属性（是一个字典）里，非命名组
    # 参数值保存在实例的 args 属性（是一个列表）里。
    # self.kwargs.get('pk') 来获取从 URL 捕获的分类 id 值。
    # 调用父类的 get_queryset 方法获得全部文章列表
    #
    '''
    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk')) #从URL 捕获的命名组参数值保存在实例的 kwargs 属性（是一个字典）里
        return super(CategoryView, self).get_queryset().filter(category=cate)


'''  #archives 视图函数
def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,  #使用 filter 来根据条件过滤
                                    created_time__month=month,
                                    ).order_by('-created_time')
    return render(request, 'blog/index.html', context={'post_list': post_list})
'''  #archives 视图函数
'''
用模型管理器（objects）的 filter 函数来过滤文章。
根据 created_time 的 year 和 month 属性过滤，筛选出文章发表在对应的 year 年和
month 月的文章。注意这里 created_time 是 Python 的 date 对象，其有一个 year 和 month 属性，我们在上一章使用过这个属性。
Python 中类实例调用属性的方法通常是 created_time.year，但是由于这里作为函数的参数列表，所以 Django 要
求我们把点替换成了****两个下划线****，即 created_time__year。同时和 index 视图中一样，
我们对返回的文章列表进行了排序。此外由于归档的下的文章列表的显示和首页是一
样的，因此我们直接渲染了 index.html 模板。

''' # 函数详解
class ArchivesView(IndexView):
    def get_queryset(self):
        return super(ArchivesView,self).get_queryset().filter(
            created_time__year=self.kwargs.get('year'),
            created_time__month=self.kwargs.get('month')
        )

'''
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)# 从django.shortcuts 模块导入的 get_object_or_404 方法
    # 其作用就是当传入的 pk 对应的Post 在数据库存在时，就返回对应的 post，如果不存在，就给用户返回一个 404 错误，表明用户请求的文章不存在。

    post.increase_views() # 阅读量 +1

    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',  #codehilite 是语法高亮拓展
                                      'markdown.extensions.toc',   # toc 则允许我们自动生成目录
                                  ])
    # 记得在顶部导入 CommentForm，这里实例化没有 request.POST 作为参数，因此表单都是空的
    form = CommentForm()

    # 获取这篇 post 下的全部评论
    comment_list = post.comment_set.all()

    # 将文章、表单、以及文章下的评论列表作为模板变量传给 detail.html 模板，以便渲染相应数据。
    context = {'post': post,   # 文章
               'form': form,   # 表单
               'comment_list': comment_list  # 评论
               }

    return render(request, 'blog/detail.html', context=context)
'''  #  detail(request, pk)
'''
#    用 Markdown 语法写的测试
#    # 一级标题
#    ## 二级标题
#    ### 三级标题
#    >引用
#    - 无序列表
#    - 无序列表
#    - 无序列表
#    [百度的链接](http://baidu.com)
#    ![图片](http://box.bdimg.com/static/fisp_static/common/img/searchbox/logo_news_276_88_1f9876a.png)
#    ```python
#    def detail(request, pk):
#        post = get_object_or_404(Post, pk=pk)
#        post.body = markdown.markdown(post.body,extensions=[
#                                                'markdown.extensions.extra',
#                                                'markdown.extensions.codehilite',
#                                                'markdown.extensions.toc',])
#    return render(request, 'blog/detail.html', context={'post':post})
#    ```

'''    #Markdown 语法
'''
# 任何的 HTML 代码在 Django 的模板中都会被转义（即显示原始的 HTML 代
# 码，而不是经浏览器渲染后的格式）。为了解除转义，只需在模板标签使用 safe 过滤
# 器即可，告诉 Django，这段文本是安全的，你什么也不用做。在模板中找到展示博
# 客文章主体的 {{ post.body }} 部分，为其加上 safe 过滤器，{{ post.body|safe }}，
# 大功告成，这下看到预期效果了。
#
# safe 过滤器，{{ post.body|safe }}，
#
# safe 是 Django 模板系统中的过滤器（Filter），可以简单地把它看成是一种函数，其
# 作用是作用于模板变量，将模板变量的值变为经过滤器处理过后的值。例如这里

blogproject/templates/blog/detail.html
{% extends 'base.html' %}

{% block main %}
<!--正文-->
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ post.created_time }}">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link">
                <a href="{{ post.get_absolute_url }}#comment-area">
                    {{ post.comment_set.count }}
                    <!-- {#      模型管理器（comment_set 是一个特殊的模型管理器）
                                还有一个 count 方法，返回的是数量，即 post 下有多少条评论，我们可以直接在模板中
                                调用这个方法：{{ post.comment_set.count }}。将评论量替换成该模板变量就可以正
                                确显示文章的评论数了。         #}-->
                    评论
                </a>
            </span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
        <div class="widget-tag-cloud">
            <ul>
                标签：
                {% for tag in post.tags.all %}
                    <li><a href="{% url 'blog:tag' tag.pk %}">#{{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</article>

<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>

    <!--表单提交-->

    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">

            <!--{# {{ form.name }}、{{ form.email }}、{{ form.url }} 等将自动渲染成表单控件，例如 <input> 控件。 #}-->
            <!--{# {{ form.name.errors }}、{{ form.email.errors }} 等将渲染表单对应字段的错误（如果
                有的话），例如用户 email 格式填错了，那么 Django 会检查用户提交的 email 的格
                式，然后将格式错误信息保存到 errors 中，模板便将错误信息渲染显示。#}-->

            <div class="col-md-4">  <!--表单提交-->
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}

            </div>
            <div class="col-md-4">  <!--表单提交-->
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">  <!--表单提交-->
                <label for="{{ form.url.id_for_label }}">网址：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">   <!--表单提交-->
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>

        </div> <!-- row -->
    </form>

    <!--评论区-->
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>4</span> 条评论</h3>

        <ul class="comment-list list-unstyled">
            <!--显示评论内容-->
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            {% empty %}
                暂无评论
            {% endfor %}

        </ul>


    </div>


</section>
{% endblock main %}


{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        {{ post.toc|safe }}
    </div>
{% endblock toc %}


blogproject/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in post_list %}
        <!--文章信息显示-->
        <article class="post post-{{ post.pk }}">
            <header class="entry-header">
                <h1 class="entry-title">    <!--显示文章标题-->
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1><!--显示文章标题-->

                <div class="entry-meta">
                    <span class="post-category">
                        <a href="{% url 'blog:category' post.category.pk %}">{{ post.category.name }}</a>
                    </span><!--post.category.name-->
                    <span class="post-date">
                        <a href="#">
                            <time class="entry-date" datetime="{{ post.created_time }}">
                                {{ post.created_time }}
                            </time>
                        </a>
                    </span><!--post.created_time-->
                    <span class="post-author">
                        <a href="#">
                            {{ post.author }}
                        </a>
                    </span><!--post.author-->
                    <span class="comments-link">
                        <a href="{{ post.get_absolute_url }}#comment-area">
                            {{ post.comment_set.count }} 评论
                        </a>
                    </span><!--评论-->
                    <span class="views-count">
                        <a href="{{ post.get_absolute_url }}">
                            {{ post.views }} 阅读
                        </a>
                    </span><!--阅读-->
                </div> <!--显示文章信息,作者评论阅读量-->
            </header>
            <!--摘要-->
            <div class="entry-content clearfix">
                <p> {{ post.excerpt }}...</p>
                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>

        {% empty %}
        <div class="no-post">暂时还没有发布的文章！</div>
        {% endfor %}

        <!-- 简单分页效果
        <div class="pagination-simple">
        <a href="#">上一页</a>
        <span class="current">第 6 页 / 共 11 页</span>
        <a href="#">下一页</a>
        </div>
        -->

<!--在模板中设置分页导航-->
<!--接下来便是在模板中设置分页导航，比如上一页、下一页的按钮，以及显示一些页面-->
<!--信息。我们这里设置和 Django 官方博客那样的分页导航样式（具体的样式见上-->
<!--图）。ListView 传递了以下和分页有关的模板变量供我们在模板中使用：-->
<!--• paginator ，即 Paginator 的实例。-->
<!--• page_obj ，当前请求页面分页对象。-->
<!--• is_paginated，是否已分页。只有当分页后页面超过两页时才算已分页。-->
<!--• object_list，请求页面的对象列表，和 post_list 等价。所以在模板中循环文章列表-->
<!--时可以选 post_list ，也可以选 object_list。-->




        <!--分页-->
        {% if is_paginated %}
        <div class="pagination-simple">
            <!-- 如果当前页还有上一页，显示一个上一页的按钮 -->
            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
            {% endif %}

            <!-- 显示当前页面信息 -->
            <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
            <!-- 如果当前页还有下一页，显示一个下一页的按钮 -->

            {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">下一页</a>
            {% endif %}

        </div>
        {% endif %}

        {% if is_paginated %}
        <div class="pagination">
            <ul>
                {% if first %}
                    <li><a href="?page=1">1</a></li>
                {% endif %}

                {% if left %}
                    {% if left_has_more %}
                        <li><span>...</span></li>
                    {% endif %}

                    {% for i in left %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}
                {% endif %}

                <li class="current"><a href="?page={{ page_obj.number }}">{{ page_obj.number }}</a></li>

                {% if right %}
                    {% for i in right %}
                    <li><a href="?page={{ i }}">{{ i }}</a></li>
                    {% endfor %}

                    {% if right_has_more %}
                    <li><span>...</span></li>
                    {% endif %}
                {% endif %}

                {% if last %}
                <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
                {% endif %}
            </ul>
        </div>
        {% endif %}


{% endblock main %}



