blogproject/blog/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

# regular expression   re正则简写
app_name = 'blog'  #' 告诉 Django 这个 urls.py 模块是属于 blog 应用的  这种技术叫做视图函数命名空间

'''
# 在 Django 中 URL 模式的
# 配置方式就是通过 url 函数将 URL 和视图函数绑定。比如 url(r'^$', views.index,
# name='index')，它的第一个参数是 URL 模式，第二个参数是视图函数 index。
# 对 url 函数 来说，第二个参数传入的值必须是一个函数
'''  # url 函数

urlpatterns = [
    # url(r'^$',views.index,name='index'),  #普通视图
    url(r'^$',views.IndexView.as_view(),name='index'),  #类视图
    #将类视图转换成函数视图非常简单，只需调用类视图的 as_view() 方法即可

    # 访问 /archives/2017/3/，那么 archives 视图函
    # 数的实际调用为：archives(request, year=2017, month=3)。
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives,name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),

    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),

    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),  # post/1
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),  # post/1

    # 标签视图函数
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),


]

blogproject/blogproject/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from blog.feeds import AllPostsRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('blog.urls',namespace='blog')),
    url(r'^', include('comments.urls')),

    url(r'^all/rss/$', AllPostsRssFeed(), name='rss'),

]

blogproject/templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<html>
    <head>
        <meta charset="UTF-8">
        <title>
            {{title}}
        </title>

        <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
        <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
        <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
        <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">

        <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
        <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
        <script src="{% static 'blog/js/pace.min.js' %}"></script>
        <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
    </head>
<body>
<!--顶部-->
    <div class="container">
        <header id="site-header">
            <div class="row">
                <div class="col-md-4 col-sm-5 col-xs-8">
                    <div class="logo">
                        <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp;White</a></h1>
                    </div>
                </div><!-- col-md-4 -->
                <div class="col-md-8 col-sm-7 col-xs-4">
                    <nav class="main-nav" role="navigation">
                        <div class="navbar-header">
                            <button type="button" id="trigger-overlay" class="navbar-toggle">
                                <span class="ion-navicon"></span>
                            </button>
                        </div>
                        <div class="collapse navbar-collapse" id="bsexample-navbar-collapse-1">
                            <ul class="nav navbar-nav navbar-right">
                                <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                                <li class="cl-effect-11"><a href="fullwidth.html" data-hover="博客">博客</a></li>
                                <li class="cl-effect-11"><a href="about.html" data-hover="关于">关于</a></li>
                                <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                            </ul>
                        </div><!-- /.navbar-collapse -->
                    </nav>
                    <div id="header-search-box">
                        <a id="search-menu" href="#"><span id="searchicon" class="ion-ios-search-strong"></span></a>
                        <div id="search-form" class="search-form">
                            <form role="search" method="get" id="searchform" action="#">
                                <input type="search" placeholder="搜索" required>
                                <button type="submit"><span class="ionios-search-strong"></span></button>
                            </form>
                        </div>
                    </div>
                </div><!-- col-md-8 -->
            </div>
        </header>
    </div>

<!--（2）设置 main-->
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-8">

                    <!--正文空间填充-->
                    {% block main %}
                    {% endblock %}

                </main>
            <!--（3）设置 aside-->
                <aside class="col-md-4">

                <!--右边框添加显示-->
                    {% block toc %}
                    {% endblock %}

                    <div class="widget widget-recent-posts">
                        <h3 class="widget-title">最新文章</h3>
                        {% get_recent_posts as recent_post_list %}
                        <ul>
                            {% for post in recent_post_list %}
                                <li>
                                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                                </li>
                            {% empty %}
                                暂无文章！
                            {% endfor %}
                        </ul>
                    </div> <!--最新文章-->
                    <div class="widget widget-archives">
                        <h3 class="widget-title">归档</h3>
                        {% archives as date_list %}
                        <ul>
                            {% for date in date_list %}
                                <li>
                                    <!--假设 date.year=2017，date.month=5，那么 {% url 'blog:archives' date.year-->
                                    <!--date.month %} 模板标签返回的值为/archives/2017/5/。-->
                                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                                    <!--{#为什么要使用 {% url %} 模板标签呢？事实上，我们把超链接的 href 属性设置#}-->
                                    <!--为 /archives/{{ date.year }}/{{ date.month }}/ 同样可以达到目的，但是这种写法是硬编-->
                                    <!--码的。虽然现在 blog:archives 视图函数对应的 URL 模式是这种形式，但是如果哪-->
                                    <!--天这个模式改变了呢？如果使用了硬编码的写法，那你需要把每一-->
                                    <!--处 /archives/{{ date.year }}/{{ date.month }}/ 修改为新的模式。但如果使用了 {%-->
                                    <!--url %} 模板标签，则不用做任何修改（相当于 Flask 中 url_for 的好处）。-->
                                </li>
                            {% empty %}
                                暂无归档！
                            {% endfor %}
                        </ul>
                    </div><!--归档-->
                    <div class="widget widget-category">
                        <h3 class="widget-title">分类</h3>
                        {% get_categories as category_list %}
                        <ul>
                            {% for category in category_list %}
                                <li>
                                <a href="{% url 'blog:category' category.pk %}">{{ category.name }} <span class="post-count">({{ category.num_posts }})</span></a>
                                </li>
                            {% empty %}
                                暂无分类！
                            {% endfor %}
                        </ul>
                    </div><!--分类-->
                    <div class="widget widget-tag-cloud">
                        <h3 class="widget-title">标签云</h3>
                        {% get_tags as tag_list %}
                        <ul>
                            {% for tag in tag_list %}
                                <li>
                                    <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
                                </li>
                            {% empty %}
                            暂无标签！
                            {% endfor %}
                        </ul>
                    </div><!--标签云-->

                    <div class="rss">
                        <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                    </div>    <!-- RSS 订阅 -->

                </aside>

            </div>
        </div>
    </div>

    <footer id="site-footer">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/" target="_blank" title="模板之家">模板之家</a></p>
                </div>
            </div>
        </div>
    </footer><!--底部  采集自-->
<!--（5）设置移动按钮-->
<!-- Mobile Menu -->
    <div class="overlay overlay-hugeinc">
        <button type="button" class="overlay-close"><span class="ionios-close-empty"></span></button>

        <nav>
            <ul>
                <li><a href="index.html">首页</a></li>
                <li><a href="full-width.html">博客</a></li>
                <li><a href="about.html">关于</a></li>
                <li><a href="contact.html">联系</a></li>
            </ul>
        </nav>

    </div><!--（5）设置移动按钮-->


    <script src="{% static 'blog/js/script.js' %}"></script>


</body>
</html>